### ISSUE TITLE
Web tests intermittently timing out

### ISSUE THREAD

**Issue by mdboom** [spacetelescope/asv#287] opened 2015-07-14 16:52 UTC
It's not every time.  See here for an example:

https://travis-ci.org/spacetelescope/asv/jobs/69812435

Any thoughts @pv?

**Comment by pv** [comment] 2015-07-14 17:20
I'm not sure it's only Python 3.4, it might have also occurred previously with other versions. Haven't been able to reproduce this on my machine.

The failure appears to be before it has run the tests (no dots in output). Possibly hangs during Selenium initialization --- in which case it's Selenium/PhantomJS bug, probably race condition.

There's however a bug in the tests in that the scope="session" specifier is in the wrong place. That's fixed in gh-288 but I don't think that is related to this issue.

**Comment by mdboom** [comment] 2015-07-14 18:19
So still a bit of an engima.  Just for more data: I noticed a failure on Python 2.7 where the first dot after the `test_web.py` is printed.

https://travis-ci.org/spacetelescope/asv/jobs/70935853

**Comment by pv** [comment] 2015-07-14 19:50
Yes, this is probably not easy to weed out...

The first dot being printed in the above job doesn't yet rule out hang during Selenium initialization --- prior to gh-288 the fixture was initialized before each test. Having session-scope may alleviate the issue slightly, however.

**Comment by pv** [comment] 2015-07-18 19:54
Potentially related: https://github.com/travis-ci/travis-ci/issues/3251

**Comment by pv** [comment] 2015-07-19 21:27
Looking at the most recent failure in https://travis-ci.org/spacetelescope/asv/jobs/71682218
it again stalled after outputting one dot. Since this is with single-session selenium, and after fixture init and before shutdown, it then probably either hangs on page load in `browser.get`, or in `httpd.shutdown` / `thread.join` for the preview http server. It seems this can be triggered locally by running multiple instances of the tests in parallel, and it appeared the hang in that case is in condition wait --- probably the condition inside `httpd.shutdown` that blocks until `serve_forever` exits. IOW, the Python builtin socketserver seems to fail to terminate for an unclear reason (waiting on socket?) sometimes.

gh-290 plugs these cases by changing the threads to daemon threads, which are shutdown on program exit, and using timed-out joins. Also, it sets timeouts to selenium (afaik, the default is int_max). So hopefully that fixes the issue finally...

**Comment by pv** [comment] 2015-08-11 15:57
The tests still seem to fail, but with the changes in gh-290 at least a traceback was produced:
https://travis-ci.org/spacetelescope/asv/jobs/75030204

On the browser side:
```
/home/travis/build/spacetelescope/asv/test/test_web.py:71: 
>           get_with_retry(browser, base_url)
/home/travis/build/spacetelescope/asv/test/tools.py:355: TimeoutException
```
and on the server side
```
127.0.0.1 - - [11/Aug/2015 04:42:22] "GET /jquery.md5.js HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/python/2.7.9/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/opt/python/2.7.9/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/python/2.7.9/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/opt/python/2.7.9/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/opt/python/2.7.9/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/opt/python/2.7.9/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
127.0.0.1 - - [11/Aug/2015 04:42:22] "GET /regressions.css HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/python/2.7.9/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/opt/python/2.7.9/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/python/2.7.9/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/opt/python/2.7.9/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/opt/python/2.7.9/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/opt/python/2.7.9/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

**Comment by pv** [comment] 2015-09-28 18:42
This seems to have got better via the changes.

**Closed by pv** 2015-09-28 18:42 UTC
Labels: bug
