### ISSUE TITLE
Testing branches other than master is failing

### ISSUE THREAD

**Issue by moorepants** [spacetelescope/asv#297] opened 2015-07-25 17:46 UTC
I have a branch "test=merge" that seems to derail a "git log" call:

```
moorepants@hanuman:bin(master)$ bash run_sympy_asv_benchmarks.sh 
· Fetching recent changes.
· Error running /usr/bin/git log --quiet --first-parent --format=format:%H test-merge
            STDOUT -------->
            
            STDERR -------->
            fatal: ambiguous argument 'test-merge': unknown revision or path not in the working tree.
            Use '--' to separate paths from revisions, like this:
            'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/home/moorepants/miniconda/bin/asv", line 9, in <module>
    load_entry_point('asv==0.1.1', 'console_scripts', 'asv')()
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/asv-0.1.1-py2.7.egg/asv/main.py", line 36, in main
    result = args.func(args)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/asv-0.1.1-py2.7.egg/asv/commands/__init__.py", line 47, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/asv-0.1.1-py2.7.egg/asv/commands/run.py", line 122, in run_from_conf_args
    skip_existing_commits=args.skip_existing_commits
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/asv-0.1.1-py2.7.egg/asv/commands/run.py", line 168, in run
    new_hashes = repo.get_hashes_from_range(spec)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/asv-0.1.1-py2.7.egg/asv/plugins/git.py", line 102, in get_hashes_from_range
    output = self._run_git(args, valid_return_codes=(0, 1), dots=False)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/asv-0.1.1-py2.7.egg/asv/plugins/git.py", line 60, in _run_git
    [self._git] + args, **kwargs)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/asv-0.1.1-py2.7.egg/asv/util.py", line 431, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/usr/bin/git log --quiet --first-parent --format=format:%H test-merge' returned non-zero exit status 128
```

**Comment by pv** [comment] 2015-07-25 19:39
You write test=merge but the log says test-merge. Is it just a typo?

**Comment by pv** [comment] 2015-07-25 19:41
Testing other branches than master worksforme.

**Comment by pv** [comment] 2015-10-18 20:25
Closing; cannot reproduce.

**Closed by pv** 2015-10-18 20:25 UTC

**Comment by tylerjereddy** [comment] 2016-10-31 18:07
I seem to be observing a similar issue, although it could be that I'm just doing something wrong.

Working with a branch of `scipy` that is itself a branch of `master`:
`asv run --bench SphericalV* -e 95eb01b`

ouput:
```
· Cloning project.
· Fetching recent changes.
· Error running /usr/bin/git rev-list --first-parent 95eb01b
            STDOUT -------->
            
            STDERR -------->
            fatal: ambiguous argument '95eb01b': unknown revision or path not in the working tree.
            Use '--' to separate paths from revisions, like this:
            'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/Users/treddy/anaconda/bin/asv", line 11, in <module>
    sys.exit(main())
  File "/Users/treddy/.local/lib/python2.7/site-packages/asv-0.3.dev1060+a14d8dc7-py2.7-macosx-10.5-x86_64.egg/asv/main.py", line 38, in main
    result = args.func(args)
  File "/Users/treddy/.local/lib/python2.7/site-packages/asv-0.3.dev1060+a14d8dc7-py2.7-macosx-10.5-x86_64.egg/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/Users/treddy/.local/lib/python2.7/site-packages/asv-0.3.dev1060+a14d8dc7-py2.7-macosx-10.5-x86_64.egg/asv/commands/run.py", line 123, in run_from_conf_args
    **kwargs
  File "/Users/treddy/.local/lib/python2.7/site-packages/asv-0.3.dev1060+a14d8dc7-py2.7-macosx-10.5-x86_64.egg/asv/commands/run.py", line 159, in run
    commit_hashes = repo.get_hashes_from_range(range_spec)
  File "/Users/treddy/.local/lib/python2.7/site-packages/asv-0.3.dev1060+a14d8dc7-py2.7-macosx-10.5-x86_64.egg/asv/plugins/git.py", line 118, in get_hashes_from_range
    output = self._run_git(args, valid_return_codes=(0, 1), dots=False)
  File "/Users/treddy/.local/lib/python2.7/site-packages/asv-0.3.dev1060+a14d8dc7-py2.7-macosx-10.5-x86_64.egg/asv/plugins/git.py", line 67, in _run_git
    return util.check_output([self._git] + args, **kwargs)
  File "/Users/treddy/.local/lib/python2.7/site-packages/asv-0.3.dev1060+a14d8dc7-py2.7-macosx-10.5-x86_64.egg/asv/util.py", line 512, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/usr/bin/git rev-list --first-parent 95eb01b' returned non-zero exit status 128
```

So, ok, I decided to try the command that `asv` is complaining about myself:
`/usr/bin/git rev-list --first-parent 95eb01b`

output (truncated for clarity):

```
3e271329aafe18f6c86a520d65492db44f934385
02de46a5464f182d3d64be5a7ee1087ae8be8646
```

So, there's a big list of scipy commit hashes. But that's not a fatal error for executing the same command, unless `asv` is expecting a single commit hash or something like that? I did some rebasing after the fact, but `git status` seems happy and my log history looks clean on top of master, so I must be missing something.

**Comment by pv** [comment] 2016-10-31 18:42
asv.conf.json in scipy is configured (due to historical reasons that are
no longer valid) so that it clones the repository from github --- so the
cloned repo is probably missing your commit.

**Comment by pv** [comment] 2016-10-31 18:43
If you run it via runtests.py, it uses the local repo. Pull requests to clean this up in scipy would be accepted.
