### ISSUE TITLE
Non-obvious errors when a package fails installing

### ISSUE THREAD

**Issue by pitrou** [spacetelescope/asv#492] opened 2016-12-05 18:08 UTC
When the matrix mentions a non-existing conda package, instead of clearly bailing out, `asv` proceeds to run the benchmarks with a nearly empty environment, which then spouts an ImportError for a random unrelated library.

**Comment by pv** [comment] 2017-02-19 15:36
I cannot reproduce this. Referring to a non-existent conda package in matrix for me produces:
```
· Creating environments.....
·· Error running /home/pauli/bin/conda install -p /home/pauli/prj/scipy/numpy/benchmarks/env/661915ef486b59840b70c89c1fc1da7b --yes six nonexistent-conda-package
             STDOUT -------->
             Fetching package metadata .........
             STDERR -------->
             
             
             PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
               - nonexistent-conda-package
             
             You can search for packages on anaconda.org with
             
                 anaconda search -t conda nonexistent-conda-package
             
             

·· Failure creating environment for conda-py2.7-nonexistent-conda-package-six
```
Indeed, environment creation is aborted if conda exits with non-zero return code.

**Comment by pv** [comment] 2017-06-22 22:30
Closing (no repro/reply)...

**Closed by pv** 2017-06-22 22:30 UTC
Labels: bug
