### ISSUE TITLE
get_date crashes

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/asv#376] opened 2016-03-03 15:03 UTC
While running ``asv`` today, I ran into a few crashes of the form:

```
[  5.99%] ··· Running time_units.time_unit_to                                                                                        7.20μs
[  6.00%] ··· Running time_units.time_very_simple_unit_parse                                                                        11.24μsTraceback (most recent call last):
  File "/disk1/data/anaconda/bin/asv", line 9, in <module>
    load_entry_point('asv==0.1.1', 'console_scripts', 'asv')()
  File "/disk1/data/anaconda/lib/python2.7/site-packages/asv/main.py", line 36, in main
    result = args.func(args)
  File "/disk1/data/anaconda/lib/python2.7/site-packages/asv/commands/__init__.py", line 47, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/disk1/data/anaconda/lib/python2.7/site-packages/asv/commands/run.py", line 122, in run_from_conf_args
    skip_existing_commits=args.skip_existing_commits
  File "/disk1/data/anaconda/lib/python2.7/site-packages/asv/commands/run.py", line 286, in run
    repo.get_date(commit_hash),
  File "/disk1/data/anaconda/lib/python2.7/site-packages/asv/plugins/git.py", line 96, in get_date
    valid_return_codes=(0, 1), dots=False).strip().split()[0]) * 1000
ValueError: invalid literal for int() with base 10: '``astropy.vo``'
```

I think the ``git`` command being isn't just returning the date, but also some diffs?

**Comment by pv** [comment] 2016-03-03 15:12
@astrofrog: can you check what the git command returns for you? What is the git version?

**Comment by pv** [comment] 2016-03-03 15:13
This is actually probably already fixed in asv's master branch.

**Comment by pv** [comment] 2016-03-03 16:47
Duplicate of gh-355

**Closed by pv** 2016-03-03 16:47 UTC
