### ISSUE TITLE
self tests stall

### ISSUE THREAD

**Issue by rbiswas4** [spacetelescope/asv#261] opened 2015-04-16 18:11 UTC
I am trying to install airspeed velocity on a OS X macbook pro laptop:
Darwin Kernel Version 14.3.0 (Yosemite 10.10.3) 

Install seemed to go without complaints
```python setup.py test
running test
running egg_info
writing requirements to asv.egg-info/requires.txt
writing asv.egg-info/PKG-INFO
writing top-level names to asv.egg-info/top_level.txt
writing dependency_links to asv.egg-info/dependency_links.txt
writing entry points to asv.egg-info/entry_points.txt
reading manifest file 'asv.egg-info/SOURCES.txt'
writing manifest file 'asv.egg-info/SOURCES.txt'
running build_ext
=========================================================================================================================================================================== test session starts ============================================================================================================================================================================
platform darwin -- Python 2.7.9 -- py-1.4.25 -- pytest-2.6.3
collected 28 items / 1 errors

test/test_benchmarks.py ...
test/test_compare.py .
test/test_conf.py ..
test/test_dev.py .....
test/test_graph.py ....
test/test_machine.py .
test/test_publish.py .
test/test_quickstart.py .
test/test_repo.py .x
test/test_results.py .
test/test_rm.py .
test/test_subprocess.py ..
test/test_workflow.py ..
```

While some of the previous tests take a bit of time to complete, I have not been able to get through the test_workflow.py at all, even after a couple of hours, but the process has not thrown any error or warnings aside from the error mentioned at the start, after which the tests commenced.

**Comment by pv** [comment] 2015-04-16 18:14
Try running with `py.test test/ -svv` and see if the output explains
why/where it stalls.

**Comment by rbiswas4** [comment] 2015-04-16 20:22
Ok, 
```
 py.test test/ -svv >& test_dump.dat
```
I did that and I can see that the stall happens (still running for about 2 hours) at 
```
7240.00%] · Generating graphs
[7260.00%] · Writing indexPASSED
test/test_workflow.py::test_continuous PASSED
test/test_workflow.py::test_find
```
There are also a few runtime errors in the output. I can't attach the file here, so I just put it in a scratch repository https://github.com/rbiswas4/scratch/blob/master/asv_res/test_dump.dat if you are interested.

**Comment by pv** [comment] 2015-04-17 08:04
From the log, you can see that what is hanging is calling `anaconda
create`, so it is fairly possible this is a bug in Anaconda. You can try
look into what causes that, and e.g. upgrading your Anaconda installation.

**Comment by pv** [comment] 2015-04-18 12:39
Ok, I misread the log --- this seems to be a failure to deal with multiprocessing errors during environment creation.

**Comment by pv** [comment] 2015-04-18 14:16
The issue is due to a multiprocessing bug, https://bugs.python.org/issue9400
Workaround in gh-262

**Comment by rbiswas4** [comment] 2015-04-18 21:18
OK that makes sense. I had tried running the exact `conda create ...` command at the prompt,
and everything was working, so it was the subprocess pipe splitting into threads that was causing the issue. I will try once gh-262 is merged.

**Comment by pv** [comment] 2015-04-19 01:40
gh-262 should fix the hang.
However, the anaconda failure has a different origin. As it works fine on linux, this may be some osx weirdess again.
You can test it before merging,
.
git remote add pv https://github.com/pv/asv.git
git fetch pv
git checkout pv/mp-bug-workaround

**Comment by pv** [comment] 2015-05-01 11:49
Ok, it is now merged. It's not 100% clear these changes will resolve the anaconda env creation failure itself, which may be due to various reasons, but at least they should make the tests fail with appropriate error messages instead hanging. 
@rbiswas4: please check if this is fixed for you now in the master branch; I don't have easy access to an OSX machine.

**Comment by pv** [comment] 2015-05-15 22:46
The stall is fixed. However, anaconda failures have been seen also by others, so discussion can continue at gh-270

**Closed by pv** 2015-05-15 22:47 UTC
